package requests

type General struct {
	Equipment                       int      `json:"Equipment"`
	BusinessPartner                 *int     `json:"BusinessPartner"`
	ValidityStartDate               *string  `json:"ValidityStartDate"`
	ValidityEndDate                 *string  `json:"ValidityEndDate"`
	EquipmentName                   *string  `json:"EquipmentName"`
	EquipmentType                   *string  `json:"EquipmentType"`
	EquipmentCategory               *string  `json:"EquipmentCategory"`
	TechnicalObjectType             *string  `json:"TechnicalObjectType"`
	GrossWeight                     *float32 `json:"GrossWeight"`
	NetWeight                       *float32 `json:"NetWeight"`
	WeightUnit                      *string  `json:"WeightUnit"`
	SizeOrDimensionText             *string  `json:"SizeOrDimensionText"`
	InventoryNumber                 *string  `json:"InventoryNumber"`
	OperationStartDate              *string  `json:"OperationStartDate"`
	OperationStartTime              *string  `json:"OperationStartTime"`
	OperationEndDate                *string  `json:"OperationEndDate"`
	OperationEndTime                *string  `json:"OperationEndTime"`
	EquipmentStandardID             *string  `json:"EquipmentStandardID"`
	EquipmentIndustryStandardName   *string  `json:"EquipmentIndustryStandardName"`
	CountryOfOrigin                 *string  `json:"CountryOfOrigin"`
	CountryOfOriginLanguage         *string  `json:"CountryOfOriginLanguage"`
	BarcodeType                     *string  `json:"BarcodeType"`
	AcquisitionDate                 *string  `json:"AcquisitionDate"`
	Manufacturer                    *int     `json:"Manufacturer"`
	ManufacturedCountry             *string  `json:"ManufacturedCountry"`
	ConstructionYear                *int     `json:"ConstructionYear"`
	ConstructionMonth               *int     `json:"ConstructionMonth"`
	ManufacturerPartNmbr            *string  `json:"ManufacturerPartNmbr"`
	ManufacturerSerialNumber        *string  `json:"ManufacturerSerialNumber"`
	MaintenancePlantBusinessPartner int      `json:"MaintenancePlantBusinessPartner"`
	MaintenancePlant                string   `json:"MaintenancePlant"`
	AssetLocation                   *string  `json:"AssetLocation"`
	AssetRoom                       *string  `json:"AssetRoom"`
	PlantSection                    *string  `json:"PlantSection"`
	WorkCenter                      *string  `json:"WorkCenter"`
	Project                         *string  `json:"Project"`
	MaintenancePlannerGroup         *string  `json:"MaintenancePlannerGroup"`
	CatalogProfile                  *string  `json:"CatalogProfile"`
	FunctionalLocation              *string  `json:"FunctionalLocation"`
	SuperordinateEquipment          *string  `json:"SuperordinateEquipment"`
	EquipInstallationPositionNmbr   *string  `json:"EquipInstallationPositionNmbr"`
	EquipmentIsAvailable            *bool    `json:"EquipmentIsAvailable"`
	EquipmentIsInstalled            *bool    `json:"EquipmentIsInstalled"`
	EquipIsAllocToSuperiorEquip     *bool    `json:"EquipIsAllocToSuperiorEquip"`
	EquipHasSubOrdinateEquipment    *string  `json:"EquipHasSubOrdinateEquipment"`
	MasterFixedAsset                *string  `json:"MasterFixedAsset"`
	FixedAsset                      *string  `json:"FixedAsset"`
	CreationDate                    *string  `json:"CreationDate"`
	LastChangeDateTime              *string  `json:"LastChangeDateTime"`
	IsMarkedForDeletion             *bool    `json:"IsMarkedForDeletion"`
}
